node {

    withEnv(['MONGO_URL=mongodb://192.168.49.2:30006/simplist']) {

        checkout scm

        env.DOCKER_API_VERSION="1.23"

        sh "git rev-parse --short HEAD > commit-id"

        tag = readFile('commit-id').replace("\n", "").replace("\r", "")
        appName = "simplist-backend"
        registryHost = "192.168.49.2:30400/"
        imageName = "${registryHost}${appName}:${tag}"
        env.BUILDIMG=imageName
        env.BUILD_TAG=tag

        stage "Install"

            sh "mvn -f simplist/backend/pom.xml install"


        stage "Test"

            try {
                sh "mvn -f simplist/backend/pom.xml test"
            } finally {
                junit 'simplist/backend/target/surefire-reports/TEST-edu.hm.simplist.SimplistApplicationTests.xml'
                junit 'simplist/backend/target/surefire-reports/TEST-edu.hm.simplist.TaskControllerMockTest.xml'
                junit 'simplist/backend/target/surefire-reports/TEST-edu.hm.simplist.TaskControllerSmokeTest.xml'
            }

        stage "Build"

            sh "docker build -t ${imageName} simplist/backend"

        stage "Push"

            sh "docker push ${imageName}"

        stage "Deploy"

            kubernetesDeploy configs: "kubernetes/simplist-backend.yaml", kubeconfigId: 'simplist_kubeconfig'

    }
}