apiVersion: v1
kind: Service
metadata:
  name: simplist-frontend
  labels:
    app: simplist-frontend
spec:
  ports:
    - port: 80
      targetPort: 3002
  selector:
    app: simplist-frontend
    tier: simplist-frontend
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplist-frontend
  labels:
    app: simplist-frontend
spec:
  selector:
    matchLabels:
      app: simplist-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: simplist-frontend
        tier: simplist-frontend
    spec:
      containers:
        - image: 192.168.49.2:30400/simplist-frontend:$BUILD_TAG
          name: simplist-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
              name: simplist-frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simplist-frontend
spec:
  rules:
    - host: simplist-frontend.192.168.49.2.xip.io
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: simplist-frontend
                port:
                  number: 80
