---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplist-backend
spec:
  selector:
    matchLabels:
      app: simplist-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: simplist-backend
    spec:
      containers:
        - name: simplist-backend
          image: 192.168.49.2:30400/simplist-backend:$BUILD_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev

---
apiVersion: v1
kind: Service
metadata:
  name: simplist-backend
  labels:
    app: simplist-backend
spec:
  selector:
    app: simplist-backend
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30010
  type: NodePort